# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotion.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'emotion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\remotion.proto\x12\x07\x65motion\"\x1e\n\x0e\x45motionMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"J\n\x17\x45valuatedEmotionMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12!\n\x07\x65motion\x18\x02 \x01(\x0e\x32\x10.emotion.Emotion*Q\n\x07\x45motion\x12\x0b\n\x07sadness\x10\x00\x12\x0b\n\x07neutral\x10\x01\x12\x0c\n\x08surprise\x10\x02\x12\x0b\n\x07\x64isgust\x10\x03\x12\x07\n\x03joy\x10\x04\x12\x08\n\x04\x66\x65\x61r\x10\x05\x32_\n\rEmotionServer\x12N\n\x0f\x43lassifyEmotion\x12\x17.emotion.EmotionMessage\x1a .emotion.EvaluatedEmotionMessage\"\x00\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTION']._serialized_start=134
  _globals['_EMOTION']._serialized_end=215
  _globals['_EMOTIONMESSAGE']._serialized_start=26
  _globals['_EMOTIONMESSAGE']._serialized_end=56
  _globals['_EVALUATEDEMOTIONMESSAGE']._serialized_start=58
  _globals['_EVALUATEDEMOTIONMESSAGE']._serialized_end=132
  _globals['_EMOTIONSERVER']._serialized_start=217
  _globals['_EMOTIONSERVER']._serialized_end=312
# @@protoc_insertion_point(module_scope)
